# Generated by Django 5.0.1 on 2024-01-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="titles",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.CharField(max_length=1000000),
        ),
    ]
